name: Tests
on: [push, pull_request]

jobs:
    gcc:
        strategy:
            matrix:
                gcc: [8, 9, 10, 11, 13]
                build_type: [Release, Debug]
            fail-fast: false
        name: "GCC ${{ matrix.gcc }}, ${{ matrix.build_type }}"
        runs-on: ubuntu-20.04
        steps:
            - name: "Install GCC"
              uses: egor-tensin/setup-gcc@v1
              with:
                version: ${{ matrix.gcc }}
            - name: "Install dependencies"
              run: sudo apt-get install -y liburing-dev
            - uses: actions/checkout@v2
            - run: cc -v
            - run: cmake -B ${{ matrix.build_type }} -DCRING_BENCHMARK=ON -DCRING_TESTS=ON -DCRING_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .
            - run: cmake --build ${{ matrix.build_type }}
            - run: ./${{ matrix.build_type }}/tests/run_test
    clang:
        strategy:
            matrix:
                clang: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
                build_type: [Release, Debug]
            fail-fast: false
        name: "Clang ${{ matrix.clang }}, ${{ matrix.build_type }}"
        runs-on: ubuntu-20.04
        steps:
            - name: "Install Clang"
              uses: egor-tensin/setup-clang@v1
              with:
                version: ${{ matrix.clang }}
            - name: "Install dependencies"
              run: sudo apt-get install -y liburing-dev
            - uses: actions/checkout@v2
            - run: cc -v
            - run: cmake -B ${{ matrix.build_type }} -DCRING_BENCHMARK=ON -DCRING_TESTS=ON -DCRING_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .
            - run: cmake --build ${{ matrix.build_type }}
            - run: ./${{ matrix.build_type }}/tests/run_test
    clang-format-check:
        runs-on: ubuntu-20.04
        steps:
            - name: "Install clang-format"
              run: sudo apt-get install -y clang-format
            - uses: actions/checkout@v2
            - run:  clang-format --dry-run --Werror $(find . -regex '.*\.\(c\|cpp\|cxx\|h\|hpp\|hxx\)$')